-- USER SQL
CREATE USER TESTSHOP IDENTIFIED BY 1111 
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER TESTSHOP QUOTA 10M ON USERS;

-- ROLES
GRANT CONNECT TO TESTSHOP ;
GRANT RESOURCE TO TESTSHOP ;

-- SYSTEM PRIVILEGES

